# Numpy review homework

1. Make a numpy matrix from a Python list of lists...

In [8]:
import numpy as np
my_Lists = [[2.1, 2.8, 2.7], [7.7, 7.8, 7.9], [3.7, 7.6, 8.9]]
print(my_Lists)

[[2.1, 2.8, 2.7], [7.7, 7.8, 7.9], [3.7, 7.6, 8.9]]


In [10]:
import numpy as np
my_Matrix = np.array(my_Lists)
print(my_Matrix)

[[2.1 2.8 2.7]
 [7.7 7.8 7.9]
 [3.7 7.6 8.9]]


2. Make a 3D numpy matrix from a Python list of lists of lists!

In [12]:
import numpy as np

list_of_lists = [
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]],
    [[13, 14, 15], [16, 17, 18]]
]
my_numpy_matrix = np.array(list_of_lists)
print(my_numpy_matrix)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


In [13]:
type(my_numpy_matrix)

numpy.ndarray

3. Create a 5x3 array of Gaussian random numbers. 

In [4]:
import numpy as np
gau = np.random.randn(5,3)
print(gau)

[[ 0.03660822 -1.04133265  0.39261375]
 [-0.64500072 -2.64856645  1.29360722]
 [ 0.47475202  0.36914796  0.70630154]
 [ 0.0148078  -1.04736126  0.32441835]
 [-0.32481758  0.93744731 -0.42288212]]


4. Write a script to go through the array created in 3. and announce (print) the value and its row and column indexes.

Hint: Use nested `for` loops - one to loop through the rows and one to loop through the columns.

In [18]:
import numpy as np
gau = np.random.randn(5, 3)
for i in range(gau.shape[0]):
    for j in range(gau.shape[1]):
        value = gau[i, j]
        print(f"value: {value}, row: {i}, column: {j}")

value: 2.012902448123441, row: 0, column: 0
value: -0.16791026254464958, row: 0, column: 1
value: 0.2516982074997594, row: 0, column: 2
value: 0.4996776906664015, row: 1, column: 0
value: 0.4105088399623078, row: 1, column: 1
value: -0.9320756033715177, row: 1, column: 2
value: -0.43266723653866823, row: 2, column: 0
value: -0.1768033057801706, row: 2, column: 1
value: -0.6812783862875021, row: 2, column: 2
value: 0.2511028754158366, row: 3, column: 0
value: -0.035955329044330624, row: 3, column: 1
value: 0.22758682877179828, row: 3, column: 2
value: 1.0161280865441102, row: 4, column: 0
value: -1.9260323284142629, row: 4, column: 1
value: 0.025473650891452832, row: 4, column: 2


5. Make an new array out of your random numbers such that the mean is 10 and the standard deviation is 3.

In [21]:
import numpy as np
gau = np.random.randn(5, 3)
mean2 = 10
std2 = 3
shifted_array = gau * std2 + mean2
print("original:")
print(gau)
print("\narray with mean 10 and STD of 3:")
print(shifted_array)

original:
[[-0.25479756 -0.82173572 -0.84448922]
 [ 0.47753042 -1.13042503 -1.40326741]
 [-0.58795708  0.44033627  0.55907358]
 [ 0.00540965  1.88353225 -0.80974345]
 [-0.24605808 -0.23301253  1.04912049]]

array with mean 10 and STD of 3:
[[ 9.23560733  7.53479285  7.46653233]
 [11.43259125  6.60872491  5.79019776]
 [ 8.23612877 11.3210088  11.67722074]
 [10.01622896 15.65059675  7.57076965]
 [ 9.26182576  9.3009624  13.14736148]]


6. Count the number of values in your new array that are below 7.

In [22]:
count7 = np.sum(shifted_array < 7)
print(f"New array that are below 7: {count7}")

New array that are below 7: 2


7. Make a numpy sequence that has the even numbers from 2 up to (and including) 20.

In [23]:
import numpy as np
even2 = np.array(np.arange(2, 21, 2))
even3 = even2.reshape((5, 2))
print(even3)

[[ 2  4]
 [ 6  8]
 [10 12]
 [14 16]
 [18 20]]


8. Get the second and third rows of your array.

In [24]:
rows = even3[1:3, :]
print("here are the second and third Rows:")
print(rows)

here are the second and third Rows:
[[ 6  8]
 [10 12]]


9. Compute the mean of the columns of your array.

In [25]:
means1 = np.mean(even3)
print("Here are the mean of the columns:")
print(means1)

Here are the mean of the columns:
11.0
